version: '3'
services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/oppia
    environment:
      - PYTHONUNBUFFERED=1
      - DISABLE_DEV_TOOLS=true
      - OPPIA_LOG_LEVEL=WARNING
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
    command: python -m scripts.run_backend_tests --test_target=core.storage.base_model.datetime_property_test